services:
  api:
    build: .
    container_name: jwt-auth-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped

  mongodb:
    image: mongo:8
    container_name: jwt-auth-mongodb
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: jwt-auth-redis
    restart: unless-stopped

volumes:
  mongo_data: